### PR TITLE
Fixing #6 the endpoint changed on March 29, 2016

### PR DESCRIPTION
**Pull request by douglasresende**
Just change the IP address used to connect to the service from ```209.133.196.250``` to ```54.173.24.177``` starting at March 29,  #2016.

Endpoint message received:
captura de tela 2016-03-29 as 10 17 05

### CODE REVIEW

**Comment by guilherme** [comment]
:+1:

**Comment by vyper** [comment]
Thanks @douglasresende! (:

**Comment by adilsoncarvalho** [comment]
mvp :clap:

**Comment by douglasresende** [comment]
:+1:

**Pull request merged**
